-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_nbr_consent_link`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_nbr_consent_link
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_nbr_consent_link` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique NbrConsentLink ID',
     `cih_type_participant_id` varchar(32)    COMMENT 'Particpant ID',
     `cih_type_packid` varchar(32)    COMMENT 'Pack ID',
     `consent_version` varchar(128)    COMMENT 'Pack ID',
     `consent_date` varchar(10)    COMMENT 'Pack ID',
     `panel` varchar(64)    COMMENT 'Panel',
     `site` varchar(64)    COMMENT 'Site',
     `centre` varchar(64)    COMMENT 'Centre',
     `processed` tinyint   DEFAULT FALSE COMMENT 'Processed' 
,
        PRIMARY KEY (`id`)
 
 
 
)  ENGINE=InnoDB  ;

 